### ISSUE TITLE
v1.7.0 todo list

### ISSUE THREAD

**Issue by buck-yeh** [buck-yeh/parsergen#5]
- [x] Replace [include guards](https://en.wikipedia.org/wiki/Include_guard) with `#pragma once`
- [x] New command line flag `-y` to say yes to all overwrites upon outputting of both `parsergen` & `scannergen`
- [x]  Grammar files & token files are defaulted as being prepended `#pragma once`. There is no way to turn this off until some use cases are observed.

**Comment by buck-yeh** [comment]
Done
